#!/bin/bash

INST="${1:-docker01}"
PORT=${2:-8001}
SSLPORT=${3:-8002}

CWD=$(pwd)
LOCATION=$(dirname "$0")

cd $LOCATION
rm -rf $LOCATION/../logs/*

NAME=jsonwebdb.$INST

docker run -dit --name $NAME \
 -p $PORT:8080 \
 -p $SSLPORT:8443 \
 -e TZ=Europe/Copenhagen \
 -e JsonWebDB_Inst=$INST \
 -e JsonWebDB_Home=/jsonwebdb \
 -e JsonWebDB_Config=config.json \
 -v /Users/alhof/Repository/JsonWebDB:/jsonwebdb \
 -v /Users/alhof/Repository/forms42/demo/dist:/dist \
jsonwebdb

./deploy $INST

cd $CWD
