#!/bin/bash

ARGS=$#
PORT=8080
INST="inst01"

CWD=$(pwd)
LOCATION=$(dirname "$0")

if [[ ARGS -gt 0 ]]
then
  INST=$1
fi

if [[ ARGS -gt 1 ]]
then
  PORT=$2
fi

cd $LOCATION
rm -rf $LOCATION/../logs/*

NAME=jsonwebdb.$INST

docker run -dit --name $NAME \
 -p $PORT:8080 \
 -e TZ=Europe/Copenhagen \
 -e JsonWebDB_Inst=$INST \
 -e JsonWebDB_Home=/jsonwebdb \
 -v /Users/alhof/Repository/JsonWebDB:/jsonwebdb \
 -v /Users/alhof/Repository/forms42/demo/dist:/dist \
jsonwebdb

./deploy $INST

cd $CWD
