#! /bin/bash

VERSION=3.0.0
LOCATION=$(dirname "$0")

cd $LOCATION/..

zip -r releases/JsonWebDB-$VERSION.zip documentation bin libraries security config schemas examples messages -x */.DS_Store */*/.DS_Store
