#! /bin/bash


if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

VERSION=$1
LOCATION=$(dirname "$0")

cd $LOCATION/..

zip -r releases/JsonWebDB-$VERSION.zip documentation bin libraries security config schemas examples messages -x */.DS_Store */*/.DS_Store
